// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Solucion.Data;

namespace Solucion.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210303022559_CambioALongNumeroTarjeta")]
    partial class CambioALongNumeroTarjeta
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Solucion.Model.Tarjeta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Bloqueada");

                    b.Property<double>("Monto");

                    b.Property<long>("Numero");

                    b.Property<int>("Pin");

                    b.HasKey("Id");

                    b.ToTable("Tarjeta");
                });
#pragma warning restore 612, 618
        }
    }
}
